name: artifact

on:
  push:
    branches:
      - main
env : 
     NAME: README.md
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
     
      - name: upload file
        uses: actions/upload-artifact@v4
        with : 
          name : ${{env.NAME}}
          path : ./${{env.NAME}}
